version: '3.7'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
    - mongodb
  mongodb:
    image: mongo
    volumes:
      - ./data-db:/data/db
    ports:
      - 27017:27017

volumes:
  postgres_data: