# Generated by Django 2.2.9 on 2020-01-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Author',
            field=models.TextField(blank=True, default=None),
        ),
    ]
